export default function Head() {
    return (
        <>
        <title>IMDb Clone</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by NextJs" />
        <link rel="icon" href="/favicon.ico" />
        </>
    )
}